### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [adnanyousef/FriendFinder#1]
Hello, I want to contribute on your project and I made a logo for Friend Finder. I can send you original files or PR, which one do you prefer? Here's the logos with different color and which one do you want to use?

![logos](https://user-images.githubusercontent.com/31902754/44879046-69b1dc00-ac5d-11e8-9a62-ba3108479e4c.png)

**Comment by adnanyousef** [comment]
I like the bottom right logo!

**Comment by tebriz159** [comment]
Okay, here's all the files about logo: https://drive.google.com/open?id=1FOFtLvz7CH1XaXjEDIHayaqlvBhdQXdl

**Comment by tebriz159** [comment]
I can send pr if you want

**Comment by adnanyousef** [comment]
If you could do so in a couple days, hang tight for a moment I just want to solidify some things before taking the first pull request. I will let you know when ready.

**Comment by tebriz159** [comment]
Okay man, I can wait. Let me know when it is ready.

**Comment by adnanyousef** [comment]
You can go ahead and make a PR now!

**Comment by tebriz159** [comment]
I sent PR, all the files are here https://drive.google.com/open?id=1FOFtLvz7CH1XaXjEDIHayaqlvBhdQXdl
you can edit it when you wnat. Thank you for using the logo!
